services:
  weaviate:
    image: semitechnologies/weaviate:1.27.6
    restart: unless-stopped
    ports:
      - "8080:8080"   # REST
      - "50051:50051" # gRPC
    environment:
      QUERY_DEFAULTS_LIMIT: '20'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'bm25'
      CLUSTER_HOSTNAME: 'node1'
